config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'store#index', as: :store_root
  end

  root to: 'visitors#index'

  resources :ovens do
    resource :cookies
    member do
      post :empty
    end
  end

  resources :orders, only: [:index]

  namespace :api do
    resources :orders, only: [:index] do
      put :fulfill, on: :member
    end
  end

  # mount MailPreview => 'mail_view' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cookie.rb
class Cookie < ActiveRecord::Base
  belongs_to :storage, polymorphic: :true

  validates :storage, presence: true

  attr_accessor :cookie_count

  def ready?
    self.baked
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :customer_name, presence: true
  validates :item, presence: true
  validates :pick_up_at, presence: true
end

app/models/oven.rb
class Oven < ActiveRecord::Base
  belongs_to :user
  has_many :cookies, as: :storage, dependent: :destroy

  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ovens, dependent: :destroy
  has_many :stored_cookies, class_name: 'Cookie', as: :storage

  before_create :setup_first_oven

  private

  def setup_first_oven
    ovens.new(name: 'My First Oven')
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::API
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < Api::BaseController
  def index
    sleep 1 unless Rails.env.test? # simulate delay in loading
    @orders = Order.all.order(created_at: :desc)
  end

  def fulfill
    @order = Order.find(params[:id])
    @order.fulfilled = true
    @order.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  before_action :authenticate_user!

  def new
    @oven = current_user.ovens.find_by!(id: params[:oven_id])
    if @oven.cookies.present?
      redirect_to @oven, alert: 'Cookies are already in the oven!'
    else
      @cookie = @oven.cookies.build
    end
  end

  def create
    @oven = current_user.ovens.find_by!(id: params[:oven_id])
    @cookies = @oven.cookies.create(cookie_batch_params)
    BakeOvenCookiesJob.set(wait: 30.seconds).perform_later(@oven)
    redirect_to oven_path(@oven), notice: 'Your cookies will be ready in a few minutes!'
  end

  private

  def cookie_batch_params
    Array.new(cookie_params[:cookie_count].to_i) { { fillings: cookie_params[:fillings] } }
  end

  def cookie_params
    params.require(:cookie).permit(:fillings, :cookie_count)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
end

app/controllers/ovens_controller.rb
class OvensController < ApplicationController
  before_action :authenticate_user!

  def index
    @ovens = current_user.ovens
  end

  def show
    @oven = current_user.ovens.find_by!(id: params[:id])
  end

  def empty
    @oven = current_user.ovens.find_by!(id: params[:id])
    @oven.cookies.select(&:ready?).each do |baked_cookie|
      baked_cookie.update!(storage: current_user)
    end
    redirect_to @oven, alert: 'Oven emptied!' if @oven.reload.cookies.empty?
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookies/new.html.erb
<h3>New Cookie for oven '<%= @oven.name %>'</h3>

<%= form_for [@oven, @cookie] do |f| %>
  <div class="row">
    <div class="small-8 columns">
      <%= f.label :fillings %>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <%= f.text_field :fillings %>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <%= f.label :cookie_count %>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <%= f.number_field :cookie_count, value: 1, in: 1..10 %>
    </div>
  </div>


  <div class="row">
    <div class="small-8 columns">
      <%= f.submit 'Mix and bake', class: 'button' %>
    </div>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% # Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark ph-2">
  <div class="container">
    <%= link_to "DigiBakery", root_path, class: 'navbar-brand' %>
    <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNav" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Order listing', orders_path, class: 'nav-link' %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : 'DigiBakery' %></title>
    <meta content="<%= content_for?(:description) ? yield(:description) : 'DigiBakery2' %>" name="description"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= side_load_stylesheets %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>

    <%= side_load_javascripts type: 'module', defer: true %>
  </body>
</html>

app/views/orders/index.html.erb
<h2>Orders</h2>
<br/>

<div data-order-table="true"></div>

app/views/ovens/index.html.erb
<h3>My Ovens</h3>

<ul class="ovens">
  <% @ovens.each do |oven| %>
    <li>
      <%= link_to oven.name, oven %>
    </li>
  <% end %>
</ul>

app/views/ovens/show.html.erb
<h3><%= @oven.name %></h3>

<div id="cookie-info" data-controller="oven-channel" data-oven-channel-id="<%= @oven.id %>">
  Cookie in oven:
  <% if @oven.cookies.present? %>
    <div id="cookie-list">
      <%= @oven.cookies.count %> cookies with <%= @oven.cookies.first.fillings.presence || "no fillings" %>
      <span id="cookie-baking-info">
        <% if @oven.cookies.all?(&:ready?) %>
          (Your Cookies are Ready)
        <% else %>
          (Your Cookies are being baked)
        <% end %>
      </span>
    </div>
    <%= button_to "Retrieve Cookie", empty_oven_path, class: 'button tiny' %>
  <% else %>
    None
  <% end %>
</div>

<br/>
<%= link_to "Prepare Cookie", new_oven_cookies_path(@oven), class: 'button' %>

app/views/pages/about.html.erb
<% content_for :title do %>
  About
<% end %>
<h3>About the Website</h3>
<p>
  This web application was created with
  <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
  from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/store/index.html.erb
<h3>Your Bakery</h3>
<div class="bakery-nav">
  <%= link_to "View your ovens", ovens_path %>
</div>

<br/>
<div class="store-inventory">
  Cookies for sale:
  <ul>
    <% current_user.stored_cookies.group_by(&:fillings).each_pair do |fillings, cookies| %>
      <li>
        <%= pluralize(cookies.count, "Cookie") %>
        with
        <%= fillings || "no filling" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/visitors/index.html.erb
<h3>Welcome to the DigiBakery</h3>